name: CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: [master, main]
  workflow_dispatch:
jobs:
  id-aws-account:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # TODO: would read work? Is this for AWS perms?
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_ACCOUNT_ROLE }}
          aws-region: us-east-1
      - name: Identify AWS account
        run: |
          aws sts get-caller-identity | jq -r '.Account' | grep -o '^[0-9]\{4\}'
  webapp-prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - name: Install infra
        working-directory: infra
        run: |
          npx pnpm install
      - name: Build infra
        working-directory: infra
        run: |
          npm run build
      - name: Prod-install lambda-express-hbs
        working-directory: lambda-express-hbs
        run: |
          npm install --production
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_ACCOUNT_ROLE }}
          aws-region: us-east-1
      - name: Deploy the app stack to the prod account
        working-directory: infra
        run: |
          npm run deploy-app-stack
      - name: Install itest
        working-directory: itest
        run: |
          npx pnpm install
      - name: itest
        working-directory: itest
        run: |
          npx pnpm test
  nextjs-prod:
    needs: webapp-prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # is this needed anywhere in this file?
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_ACCOUNT_ROLE }}
          aws-region: us-east-1
      - name: Install, build, test, deploy
        working-directory: nextjs
        run: |
          npm run install-build-test-deploy
